language: java
sudo: false
addons:
    sonarcloud:
        organization: "bentobox-world"

jdk:
    - openjdk8
    
script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report package sonar:sonar
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=BentoBoxWorld_AcidIsland

cache:
    directories:
        - '$HOME/.m2/repository'
        - '$HOME/.sonar/cache'
