language: java
sudo: false
addons:
    sonarcloud:
        organization: "tastybento-github"
        token:
            secure: $SONAR_TOKEN
        branches:
            - develop
            - master
jdk:
    - openjdk8
    
script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report package sonar:sonar

cache:
    directories:
        - '$HOME/.m2/repository'
        - '$HOME/.sonar/cache'
