############################################################################
# Config for AcidIsland V${version}
#
# Created and maintained by Tastybento with the help of Poslovitch
############################################################################
  
### World Settings ###
world:
  # Name of the world - if it does not exist then it will be generated.
  # It acts like a prefix for nether and end (e.g. BSkyBlock, BSkyBlock_nether, BSkyBlock_end)
  world-name: AcidIsland_world

  # Radius of island in blocks. (So distance between islands is twice this)  
  # Will be rounded up to the nearest 16 blocks.
  # It is the same for every dimension : Overworld, Nether and End.
  # This value cannot be changed mid-game and the plugin will not start if it is different.
  distance-between-islands: 64

  # Default protection range radius in blocks. Cannot be larger than distance.
  # Admins can change protection sizes for players individually using /bsadmin setrange
  # or set this permission: bskyblock.island.range.<number>
  protection-range: 50

  # Start islands at these coordinates. This is where new islands will start in the
  # world. These must be a factor of your island distance, but the plugin will auto
  # calculate the closest location on the grid. Islands develop around this location
  # both positively and negatively in a square grid.
  # If none of this makes sense, leave it at 0,0.
  start-x: 0
  start-z: 0

  # Island height - Lowest is 5.
  # It is the y coordinate of the bedrock block in the schematic
  island-height: 50

  # Sea height (don't changes this mid-game unless you delete the world)
  # Minimum is 0, which means you are playing Skyblock!
  # If sea height is less than about 10, then players will drop right through it
  # if it exists. Makes for an interesting variation on skyblock.
  sea-height: 55

  # Maximum number of islands in the world. Set to 0 for unlimited. 
  # If the number of islands is greater than this number, no new island will be created.
  max-islands: 0

  ### Nether-related Settings ###
  nether:
    # Generate Nether - if this is false, the nether world will not be made and access to
    # the nether will not occur. Other plugins may still enable portal usage.
    # Note: Some challenges will not be possible if there is no nether.
    # Note that with a standard nether all players arrive at the same portal and entering a
    # portal will return them back to their islands.
    generate: true

    # Islands in Nether. Change to false for standard vanilla nether.
    islands: true

    # Nether trees are made if a player grows a tree in the nether (gravel and glowstone)
    # Applies to both vanilla and islands Nether
    trees: true

    # Make the nether roof, if false, there is nothing up there
    # Change to false if lag is a problem from the generation
    # Only applies to islands Nether
    roof: true
   
    # Nether spawn protection radius - this is the distance around the nether spawn
    # that will be protected from player interaction (breaking blocks, pouring lava etc.)
    # Minimum is 0 (not recommended), maximum is 100. Default is 25.
    # Only applies to vanilla nether
    spawn-radius: 25
  
  end:
    generate: true
    islands: true

### Island Settings ###
island:
  # Default chest items
  chest-items:
  - ==: org.bukkit.inventory.ItemStack
    type: LAVA_BUCKET
  - ==: org.bukkit.inventory.ItemStack
    type: ICE
    amount: 2
  - ==: org.bukkit.inventory.ItemStack
    type: MELON_SEEDS
  - ==: org.bukkit.inventory.ItemStack
    type: BONE
    amount: 2
  - ==: org.bukkit.inventory.ItemStack
    type: COBBLESTONE
    amount: 5
  - ==: org.bukkit.inventory.ItemStack
    type: SAPLING
    amount: 2

  # Default max team size
  # Use this permission to set for specific user groups: askyblock.team.maxsize.<number> 
  # Permission size cannot be less than the default below. 
  max-team-size: 4
    
  # Default maximum number of homes a player can have. Min = 1
  # Accessed via sethome <number> or go <number>
  # Use this permission to set for specific user groups: askyblock.island.maxhomes.<number>  
  max-homes: 1

  # How long a player must wait until they can rejoin a team island after being
  # kicked in minutes. This slows the effectiveness of players repeating challenges
  # by repetitively being invited to a team island.
  invite-wait: 60

  ### Join/leave/reset island related settings ###
  reset:
    # How many resets a player is allowed (override with /asadmin clearreset <player>)
    # Value of -1 means unlimited, 0 means hardcore - no resets.
    # Example, 2 resets means they get 2 resets or 3 islands lifetime
    reset-limit: -1

    #How long a player must wait before they can reset their island again in second
    reset-wait: 300
    
    # Kicked or leaving players lose resets
    # Players who leave a team will lose an island reset chance
    # If a player has zero resets left and leaves a team, they cannot make a new
    # island by themselves and can only join a team.
    # Leave this true to avoid players exploiting free islands
    leavers-lose-resets: true
    
    # Allow kicked players to keep their inventory.
    # If false, kicked player's inventory will be thrown at the island leader if the
    # kicked player is online and in the island world.
    kicked-keep-inventory: false
    
    # What the plugin should reset when the player joins or creates an island
    on-join:
      # Reset Money - if this is true, will reset the player's money to the starting money
      # Recommendation is that this is set to true, but if you run multi-worlds
      # make sure your economy handles multi-worlds too.
      money: false

      # Reset inventory - if true, the player's inventory will be cleared.
      # Note: if you have MultiInv running or a similar inventory control plugin, that
      # plugin may still reset the inventory when the world changes.
      inventory: false

      # Reset Ender Chest - if true, the player's Ender Chest will be cleared.
      ender-chest: false

    # What the plugin should reset when the player leaves or is kicked from an island
    on-leave:
      # Reset Money - if this is true, will reset the player's money to the starting money
      # Recommendation is that this is set to true, but if you run multi-worlds
      # make sure your economy handles multi-worlds too.
      money: false

      # Reset inventory - if true, the player's inventory will be cleared.
      # Note: if you have MultiInv running or a similar inventory control plugin, that
      # plugin may still reset the inventory when the world changes.
      inventory: false

      # Reset Ender Chest - if true, the player's Ender Chest will be cleared.
      ender-chest: false

  # Removing mobs - this kills all monsters in the vicinity. Benefit is that it helps
  # players return to their island if the island has been overrun by monsters.
  # Con is that it kills any mob grinders.
  remove-mobs:
    # Remove mobs on island when logging in.
    on-login: false

    # Remove mobs when /island.
    on-island: false
    
    # Mob white list - these mobs will NOT be removed when logging in or doing /island
    whitelist:
    - WITHER
    - ENDERMAN
    - PIG_ZOMBIE
    #- ZOMBIE_VILLAGER (1.10+)

  # Make island if player teleports to the island world and does not have one
  make-island-if-none: false

  # Immediately teleport player to their island (home 1 if it exists) when entering the world
  immediate-teleport-on-island: false

  # Have player's respawn on their island if they die
  respawn-on-island: false
  
  # Only allow the island leader to coop players.
  # Island members wont be able to coop other players.
  only-leader-can-coop: false
  
  # Deaths count
  deaths:
    # Max deaths
    # If player dies more than this, it doesn't count anymore
    max: 10
    
    # Sum team deaths - if true, all the teams deaths are summed
    # If false, only the leader's deaths counts
    sum-team: false


### Acid Settings ###
acid:
  # Ops receive damage from acid (Set to true if you want Ops to play properly)
  damage-op: true

  # Damage chickens in acid - true or false - chickens tend to go swimming...
  damage-chickens: false

  damage:
    # Water is acid
    acid:
      # Acid damage to player per second by being in acid if they have no armor on.
      # A fully health player has 20 health points. Players will regen some health
      # so the default will give players about 3 seconds to get out the acid
      # 0 = no damage, 10 = default damage, 20 = instant death
      player: 10

      # Damage that monsters will experience in acid.
      monster: 5

      # Damage that animals will experience in acid.
      animal: 5

      # Destroy items in water after this many seconds. Timing is variable and may occur
      # up to 2x this time. If 0, items will not be removed. Acid damage does not need to
      # be on for this setting to work. i.e., it'll work with water too.
      # Items fizz when they are destroyed.
      item: 0

    # Damage that rain does.
    rain: 1

    # Damage type to apply in addition to acid damage
    # Types can be : SLOW, SLOW_DIGGING, CONFUSION, BLINDNESS, HUNGER, WEAKNESS and POISON
    # If you just want these to act, then make the acid damage 0 above
    # Note - these are potion effects and so can be cured by milk
    effects:
    - CONFUSION
    - BLINDNESS

  # Armor protection
  protection:
    # Protect players from acid rain if they have a helmet on
    helmet: false

    # Protect players from all acid if they have a full set of armor on
    full-armor: false

# Config.yml version. DO NOT EDIT. This number only changes if the latest
# plugin config has been updated. If a new config is detected, it will be
# auto-saved to config.new.yml.
version: ${version}
